import { Company } from '@/types'

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechFlow AI',
    description: 'AI-powered workflow automation platform for enterprises',
    industry: 'Enterprise Software',
    stage: 'Series A',
    location: 'San Francisco, CA',
    founded: 2020,
    employees: '50-100',
    website: 'https://techflow.ai',
    tags: ['AI', 'SaaS', 'Enterprise'],
    signals: [
      {
        id: 's1',
        type: 'funding',
        title: 'Raised $15M Series A',
        description: 'Led by Sequoia Capital',
        date: '2024-01-15',
      },
      {
        id: 's2',
        type: 'hiring',
        title: 'Expanding engineering team',
        description: '10+ open positions',
        date: '2024-02-01',
      },
    ],
  },
  {
    id: '2',
    name: 'GreenEnergy Solutions',
    description: 'Renewable energy management and optimization platform',
    industry: 'Clean Energy',
    stage: 'Seed',
    location: 'Austin, TX',
    founded: 2022,
    employees: '10-50',
    website: 'https://greenenergy.io',
    tags: ['CleanTech', 'Energy', 'Sustainability'],
    signals: [
      {
        id: 's3',
        type: 'product',
        title: 'Launched new dashboard',
        description: 'Real-time energy monitoring',
        date: '2024-01-20',
      },
    ],
  },
  {
    id: '3',
    name: 'HealthSync',
    description: 'Patient data synchronization platform for healthcare providers',
    industry: 'Healthcare',
    stage: 'Series B',
    location: 'Boston, MA',
    founded: 2019,
    employees: '100-500',
    website: 'https://healthsync.com',
    tags: ['Healthcare', 'SaaS', 'Data'],
    signals: [
      {
        id: 's4',
        type: 'partnership',
        title: 'Partnership with Mayo Clinic',
        description: 'Pilot program launched',
        date: '2024-02-10',
      },
    ],
  },
  {
    id: '4',
    name: 'EduLearn Platform',
    description: 'Personalized learning platform with AI tutoring',
    industry: 'EdTech',
    stage: 'Series A',
    location: 'New York, NY',
    founded: 2021,
    employees: '50-100',
    website: 'https://edulearn.com',
    tags: ['EdTech', 'AI', 'Education'],
  },
  {
    id: '5',
    name: 'FinSecure',
    description: 'Blockchain-based financial security solutions',
    industry: 'FinTech',
    stage: 'Seed',
    location: 'London, UK',
    founded: 2023,
    employees: '10-50',
    website: 'https://finsecure.io',
    tags: ['FinTech', 'Blockchain', 'Security'],
  },
  {
    id: '6',
    name: 'CloudScale',
    description: 'Infrastructure automation for cloud deployments',
    industry: 'Infrastructure',
    stage: 'Series B',
    location: 'Seattle, WA',
    founded: 2018,
    employees: '100-500',
    website: 'https://cloudscale.dev',
    tags: ['Infrastructure', 'DevOps', 'Cloud'],
  },
  {
    id: '7',
    name: 'RetailAI',
    description: 'AI-powered inventory and demand forecasting',
    industry: 'Retail Tech',
    stage: 'Series A',
    location: 'Chicago, IL',
    founded: 2020,
    employees: '50-100',
    website: 'https://retailai.com',
    tags: ['Retail', 'AI', 'Analytics'],
  },
  {
    id: '8',
    name: 'MediTrack',
    description: 'Wearable device integration for health monitoring',
    industry: 'Healthcare',
    stage: 'Seed',
    location: 'San Diego, CA',
    founded: 2022,
    employees: '10-50',
    website: 'https://meditrack.io',
    tags: ['Healthcare', 'IoT', 'Wearables'],
  },
  {
    id: '9',
    name: 'FoodChain',
    description: 'Supply chain transparency platform for food industry',
    industry: 'Food Tech',
    stage: 'Series A',
    location: 'Portland, OR',
    founded: 2021,
    employees: '50-100',
    website: 'https://foodchain.io',
    tags: ['FoodTech', 'Supply Chain', 'Blockchain'],
  },
  {
    id: '10',
    name: 'SpaceData',
    description: 'Satellite data analytics platform',
    industry: 'Space Tech',
    stage: 'Seed',
    location: 'Los Angeles, CA',
    founded: 2023,
    employees: '10-50',
    website: 'https://spacedata.io',
    tags: ['SpaceTech', 'Analytics', 'Data'],
  },
]
